### ISSUE TITLE
[Bug] DuckDuckGo command doesn't actually work

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#149]
First, does anyone even use the damn thing?

Secondly, it doesn't work.. I'll either make it work, or remove it.. Opinions matter so, tell yours..

**Comment by KingDGrizzle** [comment]
https://www.npmjs.com/package/node-duckduckgo

**Comment by theHaden** [comment]
Several people whomst'd've'ly'yaint'nt'ed'ies's'y'es I know **do** use DuckDuckGo as their primary search engine — however, I'm not sure that the command is used at all. (This is what analytics/telemetry is for, just don't go all Microsoft about it, allow people to disable it.) I don't know if it's worthwhile to keep the command developed/updated, since I've never seen a single soul use it, but who knows?

It could be worth it to keep it updated just to give people that option, but depending on how difficult it is to keep it working, it may or may not be worth it.

**Comment by vladfrangu** [comment]
For now, as the people in the [GAwesomeBot guild](https://discord.gg/NZwzJ9Q) voted, we will remove the command. It might come back in the future!
