### ISSUE TITLE
Crash on big servers

### ISSUE THREAD

**Issue by ghost** [GilbertGobbels/GAwesomeBot#230]
When the bot is in big servers and you go into the panel and under “moderation” and muted it crashes the whole bot. This server has 40k users

**Comment by TTtie** [comment]
Does this happen on a self-hosted version or on the official GAB?

**Comment by ghost** [comment]
Self-Hosted.

**Comment by ghost** [comment]
Also it’s randomly crashing when not on that page anymore

**Comment by TTtie** [comment]
Also please create the next issues according to the [ISSUE_TEMPLATE.md](https://github.com/GilbertGobbels/GAwesomeBot/blob/development/.github/ISSUE_TEMPLATE.md). This one should appear when you create a new issue; what branch, OS and node.js version do you have?

**Comment by ghost** [comment]
OS Ubuntu 16.04.3 x64

Node version 6.12.3

Apparently the build is the development build but under the self-hosting guide I did the stable install.

**Comment by wasdennnoch** [comment]
I guess a stack trace always helps as well.

**Comment by vladfrangu** [comment]
If we're talking about the master / experimental branch, we aren't focusing on those anymore. Development is also more outdated, and feature-less (WIP after all), and all our time is in the indev-4.0.2 branch. Do note that we are still undergoing rewrite.

Telling us the branch would be useful. Although from what I see, going to the muted tab is causing this. We're still to this day not sure why that tab auto filled in older versions, and I cannot tell if it's been fixed in the newer versions. Can you try https://dev.gawesomebot.com and see if that works?

Ok, EDIT: apparently the dev bot is currently offline as we're doing some debugging.

**Comment by ghost** [comment]
I’ve tried upgrading system specs and will see if it crashes

**Comment by ghost** [comment]
Doesn’t seem to be the issue

**Comment by Gilbert142** [comment]
I recommend trying the Development branch, as it might just fix your issue. I’ll close this unless your issue isn’t fixed in the later branches; let me know if you’re still having trouble!
