### ISSUE TITLE
[Request] Add a "Remove Strike" or "Edit Strike" button for each strike

### ISSUE THREAD

**Issue by KingDGrizzle** [GilbertGobbels/GAwesomeBot#57]
Currently, you can either remove all strikes, or add strikes from the Admin Panel. Would be nice if you could remove or edit a strike, through a button, so you avoid editing the Database

**Comment by cryptochrome** [comment]
*upvote*

**Comment by Chris92de** [comment]
I'll have a look and see what I can do about this.

**Comment by HilbertGilbertson** [comment]
Sounds like a good idea. Similarly, I think a means of removing strikes via command would be useful. In AB3, I added an 'unstrike' command to my instance, that supported clearing a specific strike based on its number (i.e. `unstrike @user 2` would remove the second strike on their record that shows when running `strikes @user`), or all strikes against a user (`unstrike @user all`). Something like that could be useful for AB4, but its implementation would be trickier than in AB3 due to the modlog.

**Comment by KingDGrizzle** [comment]
This would go in hand perfectly with #58

**Comment by HilbertGilbertson** [comment]
Removal in web interface: #82

**Comment by HilbertGilbertson** [comment]
This has been fulfilled in my PR and will certainly be implemented in one form or another, so I have closed the issue.

**Comment by KingDGrizzle** [comment]
Wheres my edit button tho? 😛

**Comment by HilbertGilbertson** [comment]
Remove **or** edit button. `if(remove_button || edit_button) issue.close();`
